[package]
name = "gui-helper"
version = "0.1.0"
edition = "2024"

[dependencies]
# Gui
fltk = { version = "1.5.19", features = ["fltk-bundled"] }


[build-dependencies]
builder = { path = "../builder" }
