[package]
name = "gui-helper"
version = "0.1.0"
edition = "2024"

authors = ["Adolfo GÃ³mez <dkmaster@dkmon.com>"]
license = "BSD-3-Clause"

[dependencies]
# Gui
fltk = { version = "1.5.19", features = ["fltk-bundled"] }


[build-dependencies]
builder = { path = "../builder" }
